---

- name: Demonstrates conditional nginx installation on Centos and Ubuntu
  hosts: all
  vars:
   - greeting_msg: DevOps!
   - provisioner_tool: Docker
   - automation_tool: Ansible
  tasks:
    - name: Install nginx web server in Ubuntu
      when: ( ansible_distribution == "Ubuntu" and ansible_os_family == "Debian" )
      apt: name=nginx state=latest update_cache=yes
      notify:
        - Restart nginx

    - name: Install yum-plugin-ovl in CentOS
      when: ( ansible_distribution == "CentOS" and ansible_os_family == "RedHat" )
      yum: name=yum-plugin-ovl state=latest

    - name: Do a yum update in CentOS
      when: ( ansible_distribution == "CentOS" and ansible_os_family == "RedHat" )
      yum: name=* state=latest
    
    - name: Install EPEL Release in CentOS
      when: ( ansible_distribution == "CentOS" and ansible_os_family == "RedHat" )
      yum: name=epel-release state=latest

    - name: Do a yum update in CentOS
      when: ( ansible_distribution == "CentOS" and ansible_os_family == "RedHat" )
      yum: name=* state=latest
 
    - name: Install nginx web server in Centos  
      when: ( ansible_distribution == "CentOS" and ansible_os_family == "RedHat" )
      yum: name=nginx state=latest
      notify:
        - Restart nginx
      
    - name: Create web root folder
      file: path=/var/html state=directory mode=0777

    - name: Configure nginx web root folder in Ubuntu
      when: ( ansible_distribution == "Ubuntu" and ansible_os_family == "Debian" )
      copy: src=default dest=/etc/nginx/sites-available/default
      notify:
       - Restart nginx

   # - name: Configure nginx web root folder in CentOS
    #  when: ( ansible_distribution == "CentOS" and ansible_os_family == "RedHat" )
     # copy: src=default dest=/etc/nginx/conf.d/sites-available/default.conf
      #notify:
       #- Restart nginx

    - name: Deploy web page in nginx web server
      template: src=index.html.j2 dest=/var/html/index.html

  handlers:
    - name: Restart nginx
      command: service nginx restart
